services:
  db:
    stop_grace_period: 0s
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

  backend:
    stop_grace_period: 0s
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    build: backend
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src

  frontend:
    stop_grace_period: 0s
    build: frontend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
